### ISSUE TITLE
04-dimensionality reduction kernel restart

### ISSUE THREAD

**Issue by manojneuro** [neurolibre/brainiak-tutorials#5]
@ltetrel When running the notebook 04-dimensionality reduction and 05-classifier-optimization, it seems that the kernel runs out of memory. We are loading the full data for one subject in these notebooks. Usually about 5-6GB is sufficient to load the data for this notebook. They run fine on Google Colab.

**Comment by manojneuro** [comment]
Screenshot
![image](https://user-images.githubusercontent.com/26097457/60267102-b69c2880-98e9-11e9-9a03-5cfe7d4c1821.png)

**Comment by ltetrel** [comment]
@manojneuro Our platform gives 4GB of memory guaranteed for each user, you can have up to 6GB but it depends on the workload. This is because we are not a computing platform, so every day ressources should be low if we want to handle a lot of users in parrallel (mybinder provides just 1GB [for example](https://mybinder.readthedocs.io/en/latest/faq.html#how-much-memory-am-i-given-when-using-binder)).
There are two solutions :
1. Can you reduce the amount of memory you are using ? (doing PCA on fewer samples, or downsample your data ?)
2. We can provide you more RAM for a limited period (if you are running a hackaton for few days for example)
